<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Game.Core</RootNamespace>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Assets/Game/Core/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../packages/com.nixin.game.core/DotNet~/Nixin.Game.Core.csproj" />
    <ProjectReference Include="../../../packages/com.nixin.memory.core/DotNet~/Nixin.Memory.Core.csproj" />
  </ItemGroup>
</Project>
